variables:
  strip-binaries: |
    find "%{install-root}" -type f \
      '(' -perm -111 -o -name '*.so*' \
          -o -name '*.cmxs' -o -name '*.node' ')' \
      -exec sh -ec \
      'read -n4 hdr <"$1" # check for elf header
       if [ "$hdr" != "$(printf \\x7fELF)" ]; then
           exit 0
       fi
       sysroot="%{sysroot}"
       if [ -z "${sysroot}" ]; then
         sysroot="/nonexistant"
       fi
       case "${1}" in
         "%{install-root}%{debugdir}/"*|"%{install-root}%{sysroot}%{debugdir}/"*)
           exit 0
           ;;
         "%{install-root}%{sysroot}/"*)
           realpath="$(realpath -s --relative-to="%{install-root}%{sysroot}" "$1")"
           debugfile="%{install-root}%{sysroot}%{debugdir}/${realpath}.debug"
           toolchain=%{triplet}-
           ;;
         *)
           realpath="$(realpath -s --relative-to="%{install-root}" "$1")"
           debugfile="%{install-root}%{debugdir}/${realpath}.debug"
           ;;
       esac
       if "${toolchain}objdump" -j .gnu_debuglink -s "$1" &>/dev/null; then
         exit 0
       fi
       mkdir -p "$(dirname "$debugfile")"
       "${toolchain}objcopy" %{objcopy-extract-args} "$1" "$debugfile"
       chmod 644 "$debugfile"
       "${toolchain}strip" %{strip-args} "$1"
       "${toolchain}objcopy" %{objcopy-link-args} "$debugfile" "$1"' - {} ';'
